services:
  carts.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://carts.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: carts
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  catalogue.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://catalogue.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: catalogue
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  front-end.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://front-end.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: front-end
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  kafka:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'kafka://kafka'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: kafka
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  orders.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://orders.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: orders
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  payment.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://payment.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: payment
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  shipping.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://shipping.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: shipping
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  user.sock-shop:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://user.sock-shop'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: user
    image: up9inc/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
version: '3.3'
