apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: up9-mockintosh
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: up9-mockintosh
  namespace: up9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: up9-mockintosh
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: up9-mockintosh
    spec:
      initContainers:
        - name: up9-load-files
          image: busybox
          args:
            - if [ ! -f "/config/mockintosh.yml" ] || [ ! "$(ls -A '/config/mock-data')" ]; then  
                mkdir -p /config/mock-data;
                cp /up9-mockintosh-config/mockintosh.yml /config/mockintosh.yml;
                cp /up9-mock-data/* /config/mock-data/; 
              fi
          command:
            - "/bin/sh"
            - -c
          volumeMounts:
          - mountPath: /config
            name: up9-mockintosh
          - mountPath: /up9-mockintosh-config
            name: up9-mockintosh-config
          - mountPath: /up9-mock-data
            name: up9-mock-data
      containers:
      - args:
        - cd /config && mockintosh mockintosh.yml
        command:
        - /bin/sh
        - -c
        image: testrio/mockintosh:latest
        imagePullPolicy: Always
        name: mockintosh
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: up9-mockintosh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: up9-mockintosh
          persistentVolumeClaim:
            claimName: up9-mockintosh
        - configMap:
            defaultMode: 420
            name: up9-mockintosh
          name: up9-mockintosh-config
        - configMap:
            defaultMode: 420
            name: up9-mock-data
          name: up9-mock-data
